/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health endpoint
         * @description Operational health check. Unauthenticated.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Exchange email and password for a JWT bearer token.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate an invitation token
         * @description Public (no session). Validates the raw token from the invitation e-mail link and returns the invitee's e-mail so the accept-invite page can show who is being onboarded.
         */
        get: operations["getInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/invitation/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation and set a password
         * @description Public (no session). Consumes the invitation token, sets the invitee's password and activates the account. The caller then logs in normally.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description Cross-tenant. Requires capability `manage_organizations`.
         */
        get: operations["listOrganizations"];
        put?: never;
        /** Create organization */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get organization by id */
        get: operations["getOrganizationById"];
        put?: never;
        post?: never;
        /** Delete organization */
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Requires capability `manage_users`.
         */
        get: operations["listUsers"];
        put?: never;
        /** Create user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get user by id */
        get: operations["getUserById"];
        /** Update user */
        put: operations["updateUser"];
        post?: never;
        /** Delete user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clear-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get clear settings
         * @description Invoice upstream config and registered bank accounts for the organization. The upstream token itself is never returned — only the env var name (`upstream_token_ref`). Requires `manage_clear_settings`.
         */
        get: operations["getClearSettings"];
        /**
         * Update clear settings
         * @description Update upstream config and the registered bank accounts (with CSV profiles).
         */
        put: operations["updateClearSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clear-settings/test-upstream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test the Invoice upstream connection */
        post: operations["testUpstreamConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bank-import-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bank import batches */
        get: operations["listBankImportBatches"];
        put?: never;
        /**
         * Import a bank CSV
         * @description Upload a bank CSV for a registered bank account. The file is parsed with that account's CSV profile, stored as immutable bank transactions, and a SHA-256 file hash is recorded for duplicate detection. Requires `manage_reconciliation`.
         */
        post: operations["importBankCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bank-import-batches/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse an import batch
         * @description Void the batch and its imported lines via a reversal (never a hard delete). Lines that are already matched must be unmatched first.
         */
        post: operations["reverseBankImportBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bank-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bank transactions
         * @description Searchable by transaction date, amount, counterparty, and status (電子帳簿保存法 search requirement). Requires `view_reconciliation`.
         */
        get: operations["listBankTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bank-transactions/unmatched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List unmatched bank transactions
         * @description Convenience filter for `status=unmatched` / `partially_matched`, searchable by transaction date, amount, and counterparty and sortable (same query contract as `listBankTransactions`, minus `status`). The export endpoint accepts the same filter params.
         */
        get: operations["listUnmatchedTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bank-transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get bank transaction by id */
        get: operations["getBankTransactionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/upstream/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List upstream invoices (read proxy)
         * @description Read-only proxy to NeNe Invoice. Returns open/overdue invoices with outstanding balances for matching and dunning eligibility. Clear never recomputes these figures.
         */
        get: operations["listUpstreamInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliations/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose matches for a bank transaction
         * @description Returns ranked match suggestions. Read-only — it writes nothing and finalizes nothing. A human must confirm via `confirmMatch`.
         */
        post: operations["proposeMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reconciliations */
        get: operations["listReconciliations"];
        put?: never;
        /**
         * Confirm a match (human-confirmed)
         * @description Allocate a bank transaction across one or more upstream invoices and write the resulting payment(s) to NeNe Invoice. Over-allocation beyond an invoice's outstanding is rejected; the excess is recorded as client credit. Appropriation across invoices is operator-directed. Requires `manage_reconciliation`.
         */
        post: operations["confirmMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get reconciliation by id */
        get: operations["getReconciliationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliations/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse a reconciliation
         * @description Void the upstream payment(s) and restore the invoice outstanding, recompute the bank transaction status, and reverse any client credit created by this match. Never a hard delete. Requires `manage_reconciliation`.
         */
        post: operations["reverseReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/client-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List client credits */
        get: operations["listClientCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/client-credits/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a client credit to an invoice
         * @description Apply remaining credit (or a portion) to a chosen upstream invoice via an idempotent payment. Explicit operator action only — never automatic. Requires `manage_reconciliation`.
         */
        post: operations["applyClientCredit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List manual receivables
         * @description Receivables entered directly in Clear (ADR 0014). Requires `view_reconciliation`.
         */
        get: operations["listManualReceivables"];
        put?: never;
        /**
         * Create a manual receivable
         * @description Record a receivable that has no Invoice upstream. It is a reconciliation reference (a receivable stub), not an issued invoice / 適格請求書 — Clear issues nothing and computes no tax (scope-contract X1). Requires `manage_reconciliation`.
         */
        post: operations["createManualReceivable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-receivables/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a manual receivable */
        get: operations["getManualReceivableById"];
        /**
         * Update a manual receivable
         * @description Full replace of the editable fields. A cancelled receivable cannot be edited. Requires `manage_reconciliation`.
         */
        put: operations["updateManualReceivable"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-receivable-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import manual receivables from CSV
         * @description Bulk-create receivables from a header-mapped CSV (columns: reference_number, client_name, total_cents, and optionally recipient_email, due_at, issued_at, currency). Amounts are integers in the smallest unit (¥1 = 1). Partial success: valid new rows are created, duplicate reference numbers are skipped, invalid rows are reported by line number. A header missing a required column fails the whole request (422). Requires `manage_reconciliation`.
         */
        post: operations["importManualReceivables"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/manual-receivables/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a manual receivable
         * @description Mark the receivable cancelled (a soft, audited state change — never a hard delete). An already-cancelled receivable returns 409. Requires `manage_reconciliation`.
         */
        post: operations["cancelManualReceivable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dunning-notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dunning notices
         * @description Returns all dunning send records for the organization. Requires `view_reconciliation`.
         */
        get: operations["listDunningNotices"];
        put?: never;
        /**
         * Send a dunning notice
         * @description Sends a professional overdue reminder to the client of the specified invoice. Checks eligibility (status in issued/partially_paid/overdue, outstanding > 0, pause status, minimum interval). Requires `send_dunning`.
         */
        post: operations["sendDunningNotice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dunning-notices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a dunning notice by ID */
        get: operations["getDunningNoticeById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dunning-pauses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dunning pauses
         * @description Returns dunning pause records. Pass `active_only=true` for currently paused invoices only. Requires `view_reconciliation`.
         */
        get: operations["listDunningPauses"];
        put?: never;
        /**
         * Pause dunning for an invoice
         * @description Pauses dunning for the specified invoice. Subsequent send attempts return 422 `dunning-paused` until resumed. Logged in audit trail. Requires `send_dunning`.
         */
        post: operations["pauseDunning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dunning-pauses/{invoiceId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume dunning for an invoice
         * @description Clears the active pause for the given invoice. Logged in audit trail. Requires `send_dunning`.
         */
        post: operations["resumeDunning"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/export/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export reconciled payments as CSV
         * @description UTF-8 BOM CSV; one row per reconciliation allocation. Includes bank transaction join. Suitable for accounting software import. Compliance §9 tax-advisor review gate applies. Requires `view_reconciliation`.
         */
        get: operations["exportReconciliations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/export/client-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export client credits as CSV
         * @description UTF-8 BOM CSV; one row per client credit record. Accepts the same filter params as listClientCredits so the export mirrors the list. Requires `view_reconciliation`.
         */
        get: operations["exportClientCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/export/dunning-notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export dunning notices as CSV
         * @description UTF-8 BOM CSV; one row per dunning send record (operational/audit copy). Columns reuse the dunning-notice response fields, incl. `outstanding_at_send_cents`. Accepts the same filter params as listDunningNotices so the export mirrors the list. Requires `view_reconciliation`.
         */
        get: operations["exportDunningNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/export/bank-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export bank transactions as CSV
         * @description UTF-8 BOM CSV; one row per bank transaction. Acts as the 電帳法 evidence companion export. Accepts the same filter params as listBankTransactions so the export mirrors the list. Requires `view_reconciliation`.
         */
        get: operations["exportBankTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit events
         * @description Immutable audit trail for the operator's organization, newest first. Records every state change (reconciliation, dunning, settings, user/role) with before/after snapshots. Read-only. Requires `manage_users`.
         */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details response. */
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://nene-clear.dev/problems/bank-transaction-not-found
             */
            type: string;
            /** @example Not Found */
            title: string;
            /**
             * Format: int32
             * @example 404
             */
            status: number;
            detail?: string;
            instance?: string;
        } & {
            [key: string]: unknown;
        };
        ValidationProblemDetails: components["schemas"]["ProblemDetails"] & {
            errors: components["schemas"]["ValidationError"][];
        };
        ValidationError: {
            /** @example value_date */
            field: string;
            /** @example A valid date is required. */
            message: string;
            /** @example required */
            code: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @example NeNe Clear */
            service: string;
            checks?: {
                [key: string]: "ok" | "error";
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT bearer token. */
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        UserRole: "superadmin" | "admin" | "member" | "viewer";
        /** @enum {string} */
        UserStatus: "active" | "invited";
        User: {
            /** Format: int64 */
            user_id: number;
            /**
             * Format: int64
             * @description Null for superadmin (cross-tenant).
             */
            organization_id: number | null;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
        };
        UserListResponse: {
            items: components["schemas"]["User"][];
            limit: number;
            offset: number;
            total: number;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            password?: string;
        };
        UpdateUserRequest: {
            role?: components["schemas"]["UserRole"];
            status?: components["schemas"]["UserStatus"];
        };
        Organization: {
            /** Format: int64 */
            organization_id: number;
            slug: string;
            name: string;
        };
        OrganizationListResponse: {
            items: components["schemas"]["Organization"][];
            limit: number;
            offset: number;
            total: number;
        };
        CreateOrganizationRequest: {
            slug: string;
            name: string;
        };
        /** @enum {string} */
        AccountType: "ordinary" | "current";
        BankAccount: {
            /** Format: int64 */
            bank_account_id: number;
            bank_name: string;
            bank_branch: string;
            account_type: components["schemas"]["AccountType"];
            account_number: string;
            /** @example shift_jis */
            csv_encoding: string;
            /** @example Y/m/d */
            csv_date_format: string;
            /** @description Column index holding 取引日 / 入金日. */
            csv_date_column: number;
            /** @description Column index holding the deposit (入金) amount. */
            csv_amount_column: number;
            /** @description Column index holding 摘要 / 振込依頼人 → counterparty_text. */
            csv_counterparty_column: number;
            /** @description Number of header rows to skip. */
            csv_header_rows: number;
        };
        BankAccountInput: {
            bank_name?: string;
            bank_branch?: string;
            account_type: components["schemas"]["AccountType"];
            account_number?: string;
            /** @example shift_jis */
            csv_encoding?: string;
            /** @example Y/m/d */
            csv_date_format?: string;
            csv_date_column?: number;
            csv_amount_column?: number;
            csv_counterparty_column?: number;
            csv_header_rows?: number;
        };
        ClearSettings: {
            /** Format: int64 */
            organization_id: number;
            /** Format: uri */
            upstream_base_url: string;
            /**
             * @description Name of the env var holding the upstream bearer token (never the secret).
             * @example NENE_INVOICE_BEARER_TOKEN
             */
            upstream_token_ref: string;
            /** @default 7 */
            dunning_min_interval_days: number;
            /** @description Fiscal year-end month (決算月). Null when unset. */
            fiscal_year_end_month: number | null;
            bank_accounts: components["schemas"]["BankAccount"][];
        };
        UpdateClearSettingsRequest: {
            /** Format: uri */
            upstream_base_url?: string;
            upstream_token_ref?: string;
            dunning_min_interval_days?: number;
            fiscal_year_end_month?: number | null;
            bank_accounts?: components["schemas"]["BankAccountInput"][];
        };
        UpstreamConnectionTestResponse: {
            reachable: boolean;
            detail?: string;
        };
        /** @enum {string} */
        BankImportBatchStatus: "imported" | "reversed";
        BankImportBatch: {
            /** Format: int64 */
            bank_import_batch_id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            bank_account_id: number;
            /** @description SHA-256 hex of the imported file. */
            file_hash: string;
            source_filename: string;
            row_count: number;
            status: components["schemas"]["BankImportBatchStatus"];
            /** Format: date-time */
            imported_at: string;
            /** Format: date-time */
            reversed_at: string | null;
            reversal_reason: string | null;
        };
        BankImportBatchListResponse: {
            items: components["schemas"]["BankImportBatch"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @enum {string} */
        BankTransactionStatus: "unmatched" | "partially_matched" | "matched" | "voided";
        BankTransaction: {
            /** Format: int64 */
            bank_transaction_id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            bank_import_batch_id: number;
            /** Format: int64 */
            bank_account_id: number;
            /**
             * Format: date
             * @description Bank value date (入金日 / 取引日).
             */
            value_date: string;
            /** Format: int64 */
            amount_cents: number;
            counterparty_text: string;
            status: components["schemas"]["BankTransactionStatus"];
        };
        BankTransactionListResponse: {
            items: components["schemas"]["BankTransaction"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @enum {string} */
        UpstreamInvoiceStatus: "issued" | "partially_paid" | "paid";
        /** @description Read-only model owned by NeNe Invoice. Only the fields the upstream proxy actually returns are modelled here; issued_at and overdue were removed as the response builder never emits them (#317). */
        UpstreamInvoice: {
            /** Format: int64 */
            invoice_id: number;
            invoice_number: string;
            /** Format: int64 */
            client_id: number;
            /** Format: date */
            due_at: string | null;
            /** Format: int64 */
            total_cents: number;
            /** Format: int64 */
            outstanding_cents: number;
            status: components["schemas"]["UpstreamInvoiceStatus"];
            /** @enum {string} */
            currency: "JPY";
        };
        UpstreamInvoiceListResponse: {
            items: components["schemas"]["UpstreamInvoice"][];
            total: number;
        };
        ProposeMatchRequest: {
            /** Format: int64 */
            bank_transaction_id: number;
        };
        MatchSuggestion: {
            /**
             * @description Candidate receivable type (ADR 0014).
             * @enum {string}
             */
            source: "invoice_upstream" | "manual";
            /**
             * Format: int64
             * @description Set for invoice_upstream candidates.
             */
            invoice_id: number | null;
            invoice_number: string | null;
            /**
             * Format: int64
             * @description Set for manual candidates (ADR 0014).
             */
            manual_receivable_id: number | null;
            /** @description Manual receivable document number. */
            reference_number: string | null;
            /** Format: int64 */
            amount_cents: number;
            /** Format: int64 */
            outstanding_cents: number;
            /**
             * Format: float
             * @description Confidence 0..1 (rules-based in Phase 1).
             */
            score: number;
            /** @description Why this candidate was suggested (e.g. exact amount, payer/invoice number in counterparty). */
            reason: string;
        };
        ProposeMatchResponse: {
            /** Format: int64 */
            bank_transaction_id: number;
            /** @description True when the Invoice upstream could not be reached, so only manual candidates are returned (ADR 0014 degraded mode). The UI surfaces this instead of failing the whole proposal. */
            upstream_unavailable: boolean;
            suggestions: components["schemas"]["MatchSuggestion"][];
        };
        Allocation: {
            /**
             * @description Target receivable type (ADR 0014). Defaults to invoice_upstream.
             * @default invoice_upstream
             * @enum {string}
             */
            source: "invoice_upstream" | "manual";
            /**
             * Format: int64
             * @description Required when source is invoice_upstream.
             */
            invoice_id?: number;
            /**
             * Format: int64
             * @description Required when source is manual.
             */
            manual_receivable_id?: number;
            /** Format: int64 */
            amount_cents: number;
        };
        ReconciliationAllocation: {
            /** Format: int64 */
            reconciliation_allocation_id: number;
            /** @enum {string} */
            source: "invoice_upstream" | "manual";
            /**
             * Format: int64
             * @description Set for invoice_upstream allocations.
             */
            invoice_id: number | null;
            /**
             * Format: int64
             * @description Set for manual allocations (ADR 0014).
             */
            manual_receivable_id: number | null;
            /** Format: int64 */
            amount_cents: number;
            /**
             * Format: int64
             * @description Upstream payment id (invoice_upstream only); null for manual.
             */
            payment_id: number | null;
            /** @example clear:recon:777 */
            external_reference: string | null;
        };
        ConfirmMatchRequest: {
            /** Format: int64 */
            bank_transaction_id: number;
            allocations: components["schemas"]["Allocation"][];
            /** @description Required for fee absorption; recorded in the audit trail. */
            reason_code?: string;
        };
        /** @enum {string} */
        ReconciliationStatus: "confirmed" | "reversed";
        Reconciliation: {
            /** Format: int64 */
            payment_reconciliation_id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            bank_transaction_id: number;
            status: components["schemas"]["ReconciliationStatus"];
            reason_code: string | null;
            /** Format: int64 */
            confirmed_by: number;
            allocations: components["schemas"]["ReconciliationAllocation"][];
            /** Format: date-time */
            confirmed_at: string;
            /** Format: date-time */
            reversed_at: string | null;
            reversal_reason: string | null;
        };
        ReconciliationListResponse: {
            items: components["schemas"]["Reconciliation"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @enum {string} */
        ClientCreditStatus: "open" | "voided";
        ClientCredit: {
            /** Format: int64 */
            client_credit_id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            client_id: number | null;
            /** @description Payer name for a manual-receivable credit; null for an upstream credit (client_id identifies the payer instead). ADR 0014, */
            client_name: string | null;
            /**
             * @description Which receivable the overpayment came from (ADR 0014).
             * @enum {string}
             */
            source: "invoice_upstream" | "manual";
            /**
             * Format: int64
             * @description Set for a manual-source credit; null for upstream.
             */
            manual_receivable_id: number | null;
            /** Format: int64 */
            amount_cents: number;
            /** Format: int64 */
            remaining_cents: number;
            status: components["schemas"]["ClientCreditStatus"];
            /** Format: int64 */
            source_bank_transaction_id: number;
            /** Format: int64 */
            reconciliation_id: number;
            /** Format: date-time */
            created_at: string;
        };
        ClientCreditListResponse: {
            items: components["schemas"]["ClientCredit"][];
            limit: number;
            offset: number;
            total: number;
        };
        /** @enum {string} */
        ManualReceivableStatus: "open" | "partially_paid" | "paid" | "cancelled";
        ManualReceivable: {
            /** Format: int64 */
            manual_receivable_id: number;
            /** Format: int64 */
            organization_id: number;
            /**
             * @description Discriminator vs Invoice-sourced receivables (ADR 0014); always `manual` here.
             * @enum {string}
             */
            source: "manual";
            /** @description External document number; not an invoice number Clear issues (X1). */
            reference_number: string;
            client_name: string;
            /** Format: email */
            recipient_email: string | null;
            /** Format: int64 */
            total_cents: number;
            /**
             * Format: int64
             * @description Clear-computed (= total_cents − Σ confirmed allocations).
             */
            outstanding_cents: number;
            /** @enum {string} */
            currency: "JPY";
            /** Format: date */
            issued_at: string | null;
            /**
             * Format: date
             * @description Required before the receivable can be dunned or aged.
             */
            due_at: string | null;
            status: components["schemas"]["ManualReceivableStatus"];
            created_at: string;
            updated_at: string | null;
        };
        ManualReceivableListResponse: {
            items: components["schemas"]["ManualReceivable"][];
            limit: number;
            offset: number;
            total: number;
        };
        ManualReceivableImportResult: {
            /** @description Number of receivables created. */
            created: number;
            /** @description Rows skipped as duplicates (existing reference_number). */
            skipped: number;
            errors: {
                /** @description 1-based CSV line number of the invalid row. */
                row: number;
                errors: {
                    field: string;
                    message: string;
                }[];
            }[];
        };
        CreateManualReceivableRequest: {
            reference_number: string;
            client_name: string;
            /** Format: email */
            recipient_email?: string;
            /** Format: int64 */
            total_cents: number;
            /**
             * @default JPY
             * @enum {string}
             */
            currency: "JPY";
            /** Format: date */
            issued_at?: string;
            /** Format: date */
            due_at?: string;
        };
        /** @description Full replace of the editable fields (omitting an optional field clears it). */
        UpdateManualReceivableRequest: components["schemas"]["CreateManualReceivableRequest"];
        ApplyClientCreditRequest: {
            /** Format: int64 */
            invoice_id: number;
            /** Format: int64 */
            amount_cents: number;
        };
        ReverseRequest: {
            reversal_reason: string;
        };
        DunningNotice: {
            /** Format: int64 */
            dunning_notice_id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            invoice_id: number;
            invoice_number: string;
            /** Format: int64 */
            client_id: number;
            /** Format: email */
            recipient_email: string;
            /** Format: int64 */
            outstanding_at_send_cents: number;
            /**
             * Format: date
             * @description Null when the invoice had no due date.
             */
            due_at: string | null;
            /** @example email */
            channel: string;
            /** @example 1.0 */
            template_version: string;
            /** Format: int64 */
            sent_by: number;
            /** Format: date-time */
            sent_at: string;
        };
        DunningNoticeListResponse: {
            items: components["schemas"]["DunningNotice"][];
            limit: number;
            offset: number;
            total: number;
        };
        AuditEvent: {
            /** Format: int64 */
            audit_event_id: number;
            /** Format: int64 */
            organization_id: number;
            /** @description Exact action string (see terminology registry §audit actions). */
            action: string;
            /** @description Subject record type (see terminology registry §audit entity types). */
            entity_type: string;
            /**
             * Format: int64
             * @description Subject record id; null when there is no single subject (e.g. failed login).
             */
            entity_id: number | null;
            /**
             * Format: int64
             * @description Actor user id. The implementation always writes an integer; an unauthenticated event (e.g. failed login) records 0, not null.
             */
            actor_id: number;
            /** Format: date-time */
            occurred_at: string;
            /** @description Sanitized snapshot before the change; null for creates. */
            before: {
                [key: string]: unknown;
            } | null;
            /** @description Sanitized snapshot after the change; null for deletes. */
            after: {
                [key: string]: unknown;
            } | null;
            /** @description Extra event context (e.g. invoice_id on dunning pause/resume); null when the event recorded none. */
            metadata: {
                [key: string]: unknown;
            } | null;
        };
        AuditEventListResponse: {
            items: components["schemas"]["AuditEvent"][];
            limit: number;
            offset: number;
            total: number;
        };
        DunningPause: {
            /** Format: int64 */
            dunning_pause_id: number;
            /** Format: int64 */
            invoice_id: number;
            /** Format: int64 */
            paused_by: number;
            /** Format: date-time */
            paused_at: string;
            paused_reason: string;
            /** Format: int64 */
            unpaused_by: number | null;
            /** Format: date-time */
            unpaused_at: string | null;
            is_active: boolean;
        };
        DunningPauseListResponse: {
            items: components["schemas"]["DunningPause"][];
            limit: number;
            offset: number;
            total: number;
        };
    };
    responses: {
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated but lacking the required capability. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested state change is not allowed from the current state. */
        InvalidStateTransition: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request body, query, or path parameters contain invalid values. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description The request body exceeds the configured size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The NeNe Invoice upstream is unreachable (degraded mode). */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The server encountered an unexpected condition. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        IdPath: number;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description One or more checks failed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Wrong email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user, plus the org's fiscal year-end month (surfaced here so non-admins can default date-range filters). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"] & {
                        fiscal_year_end_month?: number | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getInvitation: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invitation is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Invitation token expired (`invitation-expired`). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description The account is now active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Invitation token expired (`invitation-expired`). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Organization created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getOrganizationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getClearSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The clear settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateClearSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClearSettingsRequest"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    testUpstreamConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection test result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamConnectionTestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listBankImportBatches: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                source_filename?: string;
                status?: components["schemas"]["BankImportBatchStatus"];
                row_count_min?: number;
                row_count_max?: number;
                imported_from?: string;
                imported_to?: string;
                /** @description id | source_filename | row_count | status | imported_at */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of import batches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankImportBatchListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    importBankCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: int64 */
                    bank_account_id: number;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Import batch created with imported lines. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankImportBatch"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Duplicate import (same file hash already imported). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reverseBankImportBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseRequest"];
            };
        };
        responses: {
            /** @description Batch reversed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankImportBatch"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidStateTransition"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listBankTransactions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: components["schemas"]["BankTransactionStatus"];
                value_date_from?: string;
                value_date_to?: string;
                amount_min_cents?: number;
                amount_max_cents?: number;
                counterparty?: string;
                /** @description Sort column: value_date | amount_cents | counterparty_text | status. */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of bank transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransactionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listUnmatchedTransactions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                value_date_from?: string;
                value_date_to?: string;
                amount_min_cents?: number;
                amount_max_cents?: number;
                counterparty?: string;
                /** @description Sort column: value_date | amount_cents | counterparty_text. */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of unmatched bank transactions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransactionListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBankTransactionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bank transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listUpstreamInvoices: {
        parameters: {
            query?: {
                /** @description Comma-separated statuses, e.g. `issued,partially_paid,overdue`. Omitted = all open statuses. */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of upstream invoices (read proxy; not paginated). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpstreamInvoiceListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    proposeMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeMatchRequest"];
            };
        };
        responses: {
            /** @description Ranked suggestions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposeMatchResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listReconciliations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: components["schemas"]["ReconciliationStatus"];
                bank_transaction_id?: number;
                /** @description Match reconciliations allocated to this invoice. */
                invoice_id?: number;
                confirmed_from?: string;
                confirmed_to?: string;
                /** @description id | bank_transaction_id | status | confirmed_at */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of reconciliations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMatchRequest"];
            };
        };
        responses: {
            /** @description Reconciliation confirmed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidStateTransition"];
            /** @description Validation failed, or an allocation exceeds the invoice outstanding. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    getReconciliationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reconciliation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reverseReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseRequest"];
            };
        };
        responses: {
            /** @description Reconciliation reversed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidStateTransition"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listClientCredits: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: components["schemas"]["ClientCreditStatus"];
                client_id?: number;
                amount_min_cents?: number;
                amount_max_cents?: number;
                remaining_min_cents?: number;
                remaining_max_cents?: number;
                /** @description Inclusive lower bound on created_at (YYYY-MM-DD). */
                created_from?: string;
                /** @description Inclusive upper bound on created_at (YYYY-MM-DD). */
                created_to?: string;
                /** @description Sort column: id | client_id | amount_cents | remaining_cents | created_at. */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of client credits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCreditListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    applyClientCredit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyClientCreditRequest"];
            };
        };
        responses: {
            /** @description Credit applied; updated credit returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCredit"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    listManualReceivables: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                status?: components["schemas"]["ManualReceivableStatus"];
                /** @description Free-text substring match on reference_number or client_name. */
                q?: string;
                /** @description Inclusive lower bound on due_at (YYYY-MM-DD). */
                due_from?: string;
                /** @description Inclusive upper bound on due_at (YYYY-MM-DD). */
                due_to?: string;
                /** @description Sort column: id | due_at | total_cents | outstanding_cents | created_at. */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of manual receivables. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivableListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createManualReceivable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateManualReceivableRequest"];
            };
        };
        responses: {
            /** @description Created; the new receivable is returned. */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A receivable with this reference_number already exists in the tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getManualReceivableById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The receivable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateManualReceivable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateManualReceivableRequest"];
            };
        };
        responses: {
            /** @description Updated; the receivable is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The receivable is cancelled, or the new reference_number is already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    importManualReceivables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Import summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivableImportResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            500: components["responses"]["InternalServerError"];
        };
    };
    cancelManualReceivable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled; the receivable is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualReceivable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The receivable is already cancelled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listDunningNotices: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                invoice_number?: string;
                recipient_email?: string;
                outstanding_min_cents?: number;
                outstanding_max_cents?: number;
                sent_from?: string;
                sent_to?: string;
                sent_by?: number;
                /** @description invoice_number | recipient_email | outstanding_cents | sent_at | sent_by */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated dunning notice list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DunningNoticeListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    sendDunningNotice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    invoice_id: number;
                    /**
                     * @description Dunning escalation stage (terminology registry §stage). Optional; defaults to `initial` when omitted.
                     * @enum {string}
                     */
                    stage?: "initial" | "reminder" | "final";
                };
            };
        };
        responses: {
            /** @description Notice sent; record created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DunningNotice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    getDunningNoticeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dunning notice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DunningNotice"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDunningPauses: {
        parameters: {
            query?: {
                active_only?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated dunning pause list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DunningPauseListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    pauseDunning: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    invoice_id: number;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Pause created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DunningPause"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    resumeDunning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dunning resumed (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    exportReconciliations: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReconciliationStatus"];
                bank_transaction_id?: number;
                invoice_id?: number;
                confirmed_from?: string;
                confirmed_to?: string;
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportClientCredits: {
        parameters: {
            query?: {
                client_id?: number;
                status?: components["schemas"]["ClientCreditStatus"];
                amount_min_cents?: number;
                amount_max_cents?: number;
                remaining_min_cents?: number;
                remaining_max_cents?: number;
                created_from?: string;
                created_to?: string;
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportDunningNotices: {
        parameters: {
            query?: {
                invoice_number?: string;
                recipient_email?: string;
                outstanding_min_cents?: number;
                outstanding_max_cents?: number;
                sent_from?: string;
                sent_to?: string;
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportBankTransactions: {
        parameters: {
            query?: {
                status?: components["schemas"]["BankTransactionStatus"];
                value_date_from?: string;
                value_date_to?: string;
                amount_min_cents?: number;
                amount_max_cents?: number;
                counterparty?: string;
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                /** @description Filter by exact action string (see terminology registry §audit actions). */
                action?: string;
                /** @description Filter by subject record type (see terminology registry §audit entity types). */
                entity_type?: string;
                /** @description Filter by subject record id (use together with entity_type). */
                entity_id?: number;
                actor_id?: number;
                /** @description Inclusive lower bound on occurred_at (YYYY-MM-DD). */
                occurred_from?: string;
                /** @description Inclusive upper bound on occurred_at (YYYY-MM-DD). */
                occurred_to?: string;
                /** @description Sort column: occurred_at | action | entity_type | actor_id. */
                sort_by?: string;
                sort_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
